spring:
  config:
    activate.on-profile: local
  cloud:
    config:
      uri: ${CONFIG_STORE_URL:http://config-store.local}
      fail-fast: true
---
spring:
  config:
    activate.on-profile: stage
  cloud:
    config:
      uri: ${CONFIG_STORE_URL:http://host.docker.internal:8999}
      fail-fast: true